### ISSUE TITLE
Aufträge können nicht abgebrochen werden

### ISSUE THREAD

**Issue by Fl43cH3** [J-HB/SEP-Rescue#126]
Falls man einen Auftrag z.B. mit Koords 2|2 erstellt - läßt sich dieser erstellen, aber versucht man ihn dann zu starten kommt nur "nullKein Landeplatz gefunden!" . Es gibt jedoch keine Möglichkeit den Auftrag zu löschen

**Comment by J-HB** [comment]
https://github.com/J-HB/SEP-Rescue/commit/faaede2657f0d14f8fe12f2fa85c3a257b621b5e
