### ISSUE TITLE
Notification Sanitäteranzahl

### ISSUE THREAD

**Issue by Fl43cH3** [J-HB/SEP-Rescue#127]
Bei der Festlegung der Sanitäter gibt es keine Notification falls man Text eingibt. Keine Ahnung, ob wir mit solchen Eingaben rechnen wollen :D

**Comment by Nubb3r** [comment]
habe ich versucht zu fixen, er fängt trotzdem eine andere exception ab und zeigt "1 2 g" an

**Comment by Nubb3r** [comment]
er zeigt jetzt nichts mehr an, da ich den defaulkt ttext vom label vvon 1 2 g auf "" gesetzt hab
