### ISSUE TITLE
Aufträge zurückstellen

### ISSUE THREAD

**Issue by Fl43cH3** [J-HB/SEP-Rescue#128]
Aufträge, die mehr Sanitäter brauchen als 10 können weder gestartet noch aufgeschoben oder abgebrochen werden.
Gleiches gilt für Aufträge, die mehr Verletzte haben als unser größter Heli tragen kann.

**Comment by J-HB** [comment]
https://github.com/J-HB/SEP-Rescue/commit/4aceb4f51bdad96de60d34e4c952ce00c7b71820
