### ISSUE TITLE
Bei Programmstart ist nicht die Standardbesetzung drin sonder nur ein einziger Heli

### ISSUE THREAD

**Issue by Fl43cH3** [J-HB/SEP-Rescue#147]
Falls man nicht genügend Daten eingegeben hat oder keine Unfallart auswählt

**Comment by Fl43cH3** [comment]
Gibt man z.B. keine PLZ ein passiert nichts beim drücken von Speichern.

**Comment by J-HB** [comment]
https://github.com/J-HB/SEP-Rescue/commit/2eb768c865697fd84d5886854b387b1795d7b1b0

**Comment by J-HB** [comment]
Ist das hier gefixed @Fl43cH3 ?

**Comment by Fl43cH3** [comment]
ja

2015-07-13 15:18 GMT+02:00 Jan-Henrik Brommundt <notifications@github.com>:
