### ISSUE TITLE
Falsche Eingabe in den einstellungen bei Koords wird nicht abgefangen

### ISSUE THREAD

**Issue by Fl43cH3** [J-HB/SEP-Rescue#155]

**Comment by Nubb3r** [comment]
Hab's versucht zu fixen. Ich werfe da  eine Exception bei onOkButton mit double.parsedouble für die textfelder der Koordinaten. diese Exception wird auch wirklich geworfen, gefangen und displayexception wird auch ausgeführt, nur wird's halt nicht angezeigt ¯\_(ツ)_/¯
