### ISSUE TITLE
Einstellungen Personal

### ISSUE THREAD

**Issue by J-HB** [J-HB/SEP-Rescue#69]

**Comment by Nubb3r** [comment]
Das Einstellungen-Fenster mit Personalliste sieht total beschissen aus. Das liegt u.a. daran, dass Ich jetzt noch "Bearbeiten"- und "Entfernen"-Buttons eingefügt habe, die meines Erachtens fest zu diesen Tabellen dazugehören sollten. Deshalb würde ich vorschlagen, dass wir für bearbeiten/hinzufügen von Elementen in beiden Listen, den Erstellung-/Bearbeitungs-Kontext in separate Fenster auslagern. Das würde auch der Symmetrie helfen und das ganze Ding nicht so überladen.

Ich habe das erstmal so gemacht wie besprochen und werde einen pull-request für das Einstellungen-Fenster machen, ohne neue Knöpfe und alles in einem Fenster. Das kannst du dir dann ansehen und sagen was du davon hältst und ob auslagern nicht besser wäre.

**Comment by Nubb3r** [comment]
2 mögliche Lösungen sind nun als Pull requests verfügbar.
